language: node_js
node_js:
    - "12"
#cache:
#  yarn: true
#  directories:
#    - node_modules
script:
  - yarn
#before_deploy:
#  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
#deploy:
#  - provider: heroku
#    app: igiftu
#    api_key:
#      secure: $API_KEY
#    on:
#      branch: master